### Create email
POST http://{{emailsBaseUrl}}
Authorization: Basic {{emailAuth.usr}} {{emailAuth.pwd}}
Content-Type: application/json

{
  "value": "bruce@kickass.com"
}

> {%
    const emailId = response.body
    client.log("email id", emailId)
    client.global.set("email-id", emailId)
%}

### Get email by id
GET http://{{emailsBaseUrl}}/{{email-id}}
Authorization: Basic {{emailAuth.usr}} {{emailAuth.pwd}}

> {%
    const modified = response.body.modified
    client.log("modified", modified)
    client.global.set("email-modified", modified)
%}

### Get email by id - forbidden
GET http://{{emailsBaseUrl}}/{{email-id}}
Authorization: Basic {{emailAuthForbidden.usr}} {{emailAuthForbidden.pwd}}

### Update email
PUT http://{{emailsBaseUrl}}/{{email-id}}
Authorization: Basic {{emailAuth.usr}} {{emailAuth.pwd}}
Content-Type: application/json

{
  "value": "c.norris@kickass.com",
  "modified": "{{email-modified}}"
}
